# Generated by Django 4.0 on 2022-04-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_email_attachments_alter_email_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachments',
            field=models.FileField(blank=True, upload_to='emailtemplate_attachments'),
        ),
    ]
