# Generated by Django 4.0 on 2022-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_attachment_alter_email_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='context_json',
            field=models.CharField(max_length=1023),
        ),
    ]
